learning_log/learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pizzeria/', include('pizzeria.urls')),
    url(r'^meal_planner/', include('meal_planner.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'', include('learning_logs.urls'), name='learning_logs'),
    url(r'^users/', include('users.urls'), name='users'),
    # url(r'^learning_logs/', include('learning_logs.urls')),
    url(r'^admin/', admin.site.urls),
]

learning_log/learning_logs/urls.py
# define learning_logs url pattern

from django.conf.urls import url

from . import views

# template can not be used if app_name missing
app_name = 'learning_logs'

urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),

    # display topics
    url(r'^topics/$', views.topics, name='topics'),
    
    # display topic detail
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # add new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry.
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing a new entry.
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

learning_log/pizzeria/urls.py
# define pizzeria url pattern

from django.conf.urls import url

from . import views

app_name = 'pizzeria'
urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),

    # pizzas
    url(r'^pizzas/$', views.pizzas, name='pizzas'),

    # pizza
    url(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

learning_log/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

learning_log/users/urls.py
# define users url

from django.conf.urls import url
from django.contrib.auth.views import login

from .import views

app_name = 'users'
urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),


    # register page
    url(r'^register/$', views.register, name='register'),
]

learning_log/pizzeria/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    # Pizza
    name = models.CharField(max_length=40)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Return string
        return self.name

class Topping(models.Model):
    # Topping of pizza
    Pizza = models.ForeignKey(Pizza)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Return string
        if len(self.name) >= 50:
            return self.name[:50] + "..."
        else:
            return self.name          

learning_log/pizzeria/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Pizza


def index(request):
    # homepage of pizzeria
    return render(request, 'pizzeria/index.html')

@login_required
def pizzas(request):
    # show all menu
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}
    return render(request, 'pizzeria/pizzas.html', context)

def pizza(request, pizza_id):
    # show all details
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzeria/pizza.html', context)

learning_log/pizzeria/templates/pizzeria/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      <meta charset="utf-8">
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    <title>Pizzeria</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                     <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                         Learning log</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li> <a href="{% url 'pizzeria:pizzas' %}">Pizzas</a></li>
                    </ul>
                     <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">LOG OUT</a></li>
                        {% else %}
                        <Li><a href="{% url 'users:register' %}">REGISTER</a></Li>
                        <Li><a href="{% url 'users:login' %}">LOG IN</a></Li>
                        {% endif %}
                    </ul>
                </div>
            </div><!--/.nav-collapse -->
        </nav>
   <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                 {% block content %}{% endblock content %}
            </div>    
        </div><!-- container -->
</body>
</html>

learning_log/pizzeria/templates/pizzeria/index.html
{% extends "pizzeria/base.html" %}

{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <p>Here is our menu.</p>
        
    </div>

{% endblock content %}

learning_log/pizzeria/templates/pizzeria/pizza.html
{% extends "pizzeria/base.html" %}


{% block header %}
    <h1>{{ pizza }}</h1>
{% endblock header %}

{% block content %}
    <div class="container">
        <h3>Toppings</h3>
        <ul>
            {% for topping in toppings %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        {{ topping.date_added|date:'M d, Y H:i'}}
                    </h4>
                </div>
            </div>
            <div class="panel-body">
                {{ topping.name|linebreaks }}
            </div>
            {% empty %}
            No toppings have been added yet.
            {% endfor %}
        </ul>
    </div>

{% endblock content %}

learning_log/pizzeria/templates/pizzeria/pizzas.html
{% extends "pizzeria/base.html" %}

{% block header %}
    <div class="jumbotton">
        <h1>Menu</h1>
    </div>
{% endblock header %}

{% block content %}
    <div class="container">
         <ul>
            {% for pizza in pizzas %}
            <li><h4>
                <a href="{% url 'pizzeria:pizza' pizza.id %}">{{ pizza }}</a>
            </h4></li>
            {% empty %}
            <li>No pizzas have been added yet.</li>
            {% endfor %}
        </ul>
    </div>

{% endblock content %}