learning_log/learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pizzeria/', include('pizzeria.urls')),
    url(r'^meal_planner/', include('meal_planner.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'', include('learning_logs.urls'), name='learning_logs'),
    url(r'^users/', include('users.urls'), name='users'),
    # url(r'^learning_logs/', include('learning_logs.urls')),
    url(r'^admin/', admin.site.urls),
]

learning_log/learning_logs/urls.py
# define learning_logs url pattern

from django.conf.urls import url

from . import views

# template can not be used if app_name missing
app_name = 'learning_logs'

urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),

    # display topics
    url(r'^topics/$', views.topics, name='topics'),
    
    # display topic detail
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # add new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry.
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing a new entry.
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

learning_log/pizzeria/urls.py
# define pizzeria url pattern

from django.conf.urls import url

from . import views

app_name = 'pizzeria'
urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),

    # pizzas
    url(r'^pizzas/$', views.pizzas, name='pizzas'),

    # pizza
    url(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

learning_log/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

learning_log/users/urls.py
# define users url

from django.conf.urls import url
from django.contrib.auth.views import login

from .import views

app_name = 'users'
urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),

    # logout page
    url(r'^logout/$', views.logout_view, name='logout'),


    # register page
    url(r'^register/$', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    # Learning Topics
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        # Return string
        return self.text

class Entry(models.Model):
    # knowledge about one topic
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Return string
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        else:
            return self.text                                                                                  

learning_log/learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def index(request):
    # homepage of leanring logs
    return render(request, 'learning_logs/index.html')
    # return HttpResponse("Hello, world. You're at the polls index.")

@login_required
def topics(request):
    # show all topics
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    # display detail info of specific topic
    topic = Topic.objects.get(id=topic_id)
    
    # confirm login user
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    # add new topic
    if request.method != 'POST':
        # create a new form if no submit received
        form = TopicForm()
    else:
        # process submitted data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()        
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic_id]))
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit specific entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm(instance=entry)        
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        
        <title>Learning Log</title>
    </head>
    <body>
        <!-- static nav bar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                     <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                         Learning log</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
                        <li><a href="{% url 'pizzeria:pizzas' %}">Food Delivery</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a>Hello, {{ user.username }}.</a></li>
                        <li><a href="{% url 'users:logout' %}">LOG OUT</a></li>
                        {% else %}
                        <Li><a href="{% url 'users:register' %}">REGISTER</a></Li>
                        <Li><a href="{% url 'users:login' %}">LOG IN</a></Li>
                        {% endif %}
                    </ul>
                </div>
            </div><!--/.nav-collapse -->
        </nav>
        <div class="container">
            <div class="page-header">
                {% block header %}{% endblock header %}
            </div>
            <div>
                 {% block content %}{% endblock content %}
            </div>    
        </div><!-- container -->
       
    </body>
</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Edit entry:</p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>save changes</button>
  </form>
    
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotton">
        <h1>Track your leanring.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h4>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own leanring log, and list the topics you're learning about.
    </h4>
    <h4>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
    </h4>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    
  <p>Add a new entry:</p>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>
    
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}


{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}

        {% bootstrap_form form %}
        
        <!-- {{ form.as_p }} has been replaced-->
        
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>{{ topic }}</h1>
{% endblock header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                        </small>
                    </h4>
                </div>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>

        {% empty %}
            There is no entry for this topic yet.
        {% endfor%}
    </ul>

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li><h4>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </h4></li>
        {% empty %}
        <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

    <h4><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
{% endblock content %}